# Go to https://data.cms.gov/public-provider-enrollment and click through to
# find this URL.
url: https://data.cms.gov/api/views/n48j-8qtj/rows.csv
format: pecos-secondary-specialty
update_frequency: inconsistent
