# Go to https://data.cms.gov/public-provider-enrollment and click through to
# find this URL.
url: https://data.cms.gov/api/views/je57-c47h/rows.csv
schema: pecos-address
update_frequency: inconsistent
format: csv
