# Go to https://data.cms.gov/public-provider-enrollment and click through to
# find this URL.
url: https://data.cms.gov/api/views/ykfi-ffzq/rows.csv
format: pecos-enrollment
update_frequency: inconsistent
