# Go to https://data.cms.gov/public-provider-enrollment and click through to
# find this URL.
url: https://data.cms.gov/api/views/rta9-bts3/rows.csv
format: pecos-reassignment
update_frequency: inconsistent
